<?php

/**
 * Implements hook_theme().
 */
function my_theme_theme() {
  return array(
    'custom_list' => [
      'variables' => [
        'title' => '',

        'list_items' => [
          [
            'title' => '',
            'author' => '',
            'description' => '',
          ],
        ],

      ],
      'template' => 'custom-list--item',
      'render element' => 'element',
    ],
  );
}
